*** Starting uWSGI 2.0.18 (64bit) on [Tue Jun 23 22:42:49 2020] ***
compiled with version: 7.4.0 on 31 January 2020 10:32:09
os: Linux-4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019
nodename: VM-32-8-ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/git/django_project
your processes number limit is 7079
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
Python main interpreter initialized at 0x557464a85570
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x557464a85570 pid: 24691 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24691)
spawned uWSGI worker 1 (pid: 24693, cores: 2)
spawned uWSGI worker 2 (pid: 24694, cores: 2)
spawned uWSGI worker 3 (pid: 24695, cores: 2)
spawned uWSGI worker 4 (pid: 24696, cores: 2)
[pid: 24693|app: 0|req: 1/1] 113.69.34.142 () {46 vars in 935 bytes} [Tue Jun 23 22:43:05 2020] GET /video/ => generated 58997 bytes in 1080 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 2/2] 113.69.34.142 () {46 vars in 953 bytes} [Tue Jun 23 22:43:34 2020] GET /admin/view_log/ => generated 0 bytes in 12 msecs (HTTP/1.1 302) 7 headers in 265 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 3/3] 113.69.34.142 () {46 vars in 911 bytes} [Tue Jun 23 22:43:34 2020] GET /admin/login.html => generated 5348 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 319 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 4/4] 113.69.34.142 () {52 vars in 1013 bytes} [Tue Jun 23 22:50:09 2020] POST /admin/login.html => generated 145 bytes in 99 msecs (HTTP/1.1 500) 2 headers in 96 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 5/5] 113.69.34.142 () {48 vars in 942 bytes} [Tue Jun 23 22:50:15 2020] GET /admin/login.html => generated 5348 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 319 bytes (1 switches on core 0)
[pid: 24696|app: 0|req: 1/6] 113.69.34.142 () {52 vars in 1013 bytes} [Tue Jun 23 22:50:21 2020] POST /admin/login.html => generated 145 bytes in 166 msecs (HTTP/1.1 500) 2 headers in 96 bytes (1 switches on core 0)
[pid: 24696|app: 0|req: 2/7] 113.69.34.142 () {48 vars in 942 bytes} [Tue Jun 23 22:50:27 2020] GET /admin/login.html => generated 5348 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 319 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 6/8] 113.69.34.142 () {52 vars in 1013 bytes} [Tue Jun 23 22:50:50 2020] POST /admin/login.html => generated 145 bytes in 5 msecs (HTTP/1.1 500) 2 headers in 96 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 7/9] 113.69.34.142 () {48 vars in 922 bytes} [Tue Jun 23 22:50:56 2020] GET /video/ => generated 58997 bytes in 409 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 8/10] 113.69.34.142 () {48 vars in 942 bytes} [Tue Jun 23 23:01:51 2020] GET /admin/login.html => generated 5348 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 319 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 9/11] 113.69.34.142 () {52 vars in 1013 bytes} [Tue Jun 23 23:01:57 2020] POST /admin/login.html => generated 63 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 294 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 10/12] 113.69.34.142 () {46 vars in 929 bytes} [Tue Jun 23 23:01:57 2020] GET /admin/ => generated 30034 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
--------2020-06-23 23:02:10 站点1开始更新--------
--------2020-06-23 23:02:11 站点2开始更新--------
./video/func/GetPageData.py:120: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not html:
站点1今日更新： 196
[pid: 24694|app: 0|req: 1/13] 113.69.34.142 () {46 vars in 937 bytes} [Tue Jun 23 23:02:14 2020] GET /admin/view_log/ => generated 17473 bytes in 173 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
站点2今日更新： 480
[pid: 24694|app: 0|req: 2/14] 113.69.34.142 () {46 vars in 959 bytes} [Tue Jun 23 23:02:18 2020] GET /admin/view_log/?page=1 => generated 17548 bytes in 4 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
[pid: 24694|app: 0|req: 3/15] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:02:24 2020] GET /admin/view_log/?page=1 => generated 17603 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
已更新200条数据
--------2020-06-23 23:02:32 站点1更新完成--------
[pid: 24693|app: 0|req: 12/16] 113.69.34.142 () {46 vars in 904 bytes} [Tue Jun 23 23:02:10 2020] GET /admin/update/?url_index=1&type=today => generated 82 bytes in 21904 msecs (HTTP/1.1 200) 5 headers in 149 bytes (1 switches on core 1)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('18', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('18', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('18', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('18', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('19', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('19', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('19', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('19', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('13', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('13', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('13', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('13', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('10', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('10', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('10', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('10', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('7', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('7', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('7', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('7', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('3', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('3', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('3', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('3', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('2', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('2', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('2', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('2', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('1', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('1', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('1', '请求无数据，放入错误列表')
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./video/func/GetPageData.py", line 87, in wrapper
    func(obj)
  File "./video/func/GetPageData.py", line 156, in add_page_to_queue
    logger.error('page:', url.split('?p=')[1], '请求无数据，放入错误列表')
Message: 'page:'
Arguments: ('1', '请求无数据，放入错误列表')
已更新320条数据
出现错误页面： ['18', '19', '13', '10', '7', '3', '2', '1']
--------2020-06-23 23:03:09 站点2更新完成--------
[pid: 24693|app: 0|req: 12/17] 113.69.34.142 () {46 vars in 904 bytes} [Tue Jun 23 23:02:11 2020] GET /admin/update/?url_index=2&type=today => generated 82 bytes in 58041 msecs (HTTP/1.1 200) 5 headers in 149 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 13/18] 113.69.34.142 () {48 vars in 966 bytes} [Tue Jun 23 23:04:14 2020] GET /video/ => generated 58997 bytes in 423 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 1)
[pid: 24694|app: 0|req: 4/19] 113.69.34.142 () {46 vars in 953 bytes} [Tue Jun 23 23:04:59 2020] GET /admin/view_log/ => generated 22008 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 14/20] 113.69.34.142 () {46 vars in 946 bytes} [Tue Jun 23 23:05:09 2020] GET /admin/view_log/ => generated 22008 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 15/21] 113.69.34.142 () {46 vars in 959 bytes} [Tue Jun 23 23:05:11 2020] GET /admin/view_log/?page=9 => generated 19389 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 16/22] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:05:16 2020] GET /admin/view_log/?page=1 => generated 22008 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
[pid: 24693|app: 0|req: 17/23] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:08:50 2020] GET /admin/view_log/?page=2 => generated 22123 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
[pid: 24693|app: 0|req: 18/24] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:08:54 2020] GET /admin/view_log/?page=9 => generated 19554 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Tue Jun 23 23:11:58 2020] ***
compiled with version: 7.4.0 on 31 January 2020 10:32:09
os: Linux-4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019
nodename: VM-32-8-ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/git/django_project
your processes number limit is 7079
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
Python main interpreter initialized at 0x561e76333570
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416720 bytes (406 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561e76333570 pid: 25442 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25442)
spawned uWSGI worker 1 (pid: 25448, cores: 2)
spawned uWSGI worker 2 (pid: 25449, cores: 2)
spawned uWSGI worker 3 (pid: 25450, cores: 2)
spawned uWSGI worker 4 (pid: 25451, cores: 2)
[pid: 25448|app: 0|req: 1/1] 113.69.34.142 () {48 vars in 997 bytes} [Tue Jun 23 23:12:04 2020] GET /admin/view_log/?page=9 => generated 19858 bytes in 395 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
[pid: 25448|app: 0|req: 2/2] 113.69.34.142 () {46 vars in 935 bytes} [Tue Jun 23 23:12:07 2020] GET /admin/ => generated 30033 bytes in 5 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 1)
--------2020-06-23 23:12:10 站点1开始更新--------
[pid: 25451|app: 0|req: 2/3] 113.69.34.142 () {46 vars in 937 bytes} [Tue Jun 23 23:12:11 2020] GET /admin/view_log/ => generated 22008 bytes in 37 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
[pid: 25448|app: 0|req: 3/4] 113.69.34.142 () {46 vars in 959 bytes} [Tue Jun 23 23:12:13 2020] GET /admin/view_log/?page=9 => generated 20056 bytes in 24 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
./video/func/GetPageData.py:120: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not html:
站点1今日更新： 196
[pid: 25448|app: 0|req: 4/5] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:12:15 2020] GET /admin/view_log/?page=9 => generated 20342 bytes in 57 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
已更新200条数据
--------2020-06-23 23:12:23 站点1更新完成--------
[pid: 25451|app: 0|req: 2/6] 113.69.34.142 () {46 vars in 904 bytes} [Tue Jun 23 23:12:10 2020] GET /admin/update/?url_index=1&type=today => generated 82 bytes in 13053 msecs (HTTP/1.1 200) 5 headers in 149 bytes (1 switches on core 0)
[pid: 25451|app: 0|req: 3/7] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:13:19 2020] GET /admin/view_log/?page=9 => generated 20548 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 1)
[pid: 25448|app: 0|req: 5/8] 113.69.34.142 () {46 vars in 935 bytes} [Tue Jun 23 23:13:26 2020] GET /admin/ => generated 30033 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
--------2020-06-23 23:13:28 站点2开始更新--------
[pid: 25448|app: 0|req: 7/9] 113.69.34.142 () {46 vars in 937 bytes} [Tue Jun 23 23:13:29 2020] GET /admin/view_log/ => generated 22008 bytes in 24 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
./video/func/GetPageData.py:120: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not html:
站点2今日更新： 480
[pid: 25448|app: 0|req: 8/10] 113.69.34.142 () {46 vars in 959 bytes} [Tue Jun 23 23:13:31 2020] GET /admin/view_log/?page=9 => generated 20977 bytes in 48 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
[pid: 25448|app: 0|req: 9/11] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:13:34 2020] GET /admin/view_log/?page=9 => generated 21032 bytes in 92 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
[pid: 25448|app: 0|req: 10/12] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:13:41 2020] GET /admin/view_log/?page=9 => generated 21087 bytes in 75 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
[pid: 25448|app: 0|req: 11/13] 113.69.34.142 () {46 vars in 966 bytes} [Tue Jun 23 23:13:52 2020] GET /admin/view_log/?page=9 => generated 21142 bytes in 96 msecs (HTTP/1.1 200) 5 headers in 152 bytes (1 switches on core 0)
已更新480条数据
--------2020-06-23 23:13:57 站点2更新完成--------
[pid: 25448|app: 0|req: 11/14] 113.69.34.142 () {46 vars in 904 bytes} [Tue Jun 23 23:13:28 2020] GET /admin/update/?url_index=2&type=today => generated 82 bytes in 29337 msecs (HTTP/1.1 200) 5 headers in 149 bytes (1 switches on core 1)
                                                                                                                                                                                                                                